#task and data, not exist ops 
#FROM openjdk:8-jdk-alpine
# the limit resource set 320M*80%=256M
FROM rjzjh/jdk8:1
# me
MAINTAINER andy "rjzjh@163.com"
#
LABEL version="2.0.0"
LABEL location="Shang Hai" author="andy" role="Task"


RUN addgroup -S duckula && adduser -S -G duckula duckula
RUN set -ex; \
    mkdir -p /data/duckula-data; \
    apk update upgrade; \
    apk add --no-cache --virtual .must  \
         'su-exec>=0.2' \
          bash; \
    apk add --no-cache --virtual .duckuladepent  \
          tar; 
COPY ./duckula.tar  /opt/
COPY ./duckula-data.tar  /data/
COPY ./export/config.yaml  /
COPY ./export/jmx_prometheus_javaagent-0.3.1.jar  /
RUN tar -xf /opt/duckula.tar -C /opt/ --strip-components=0; \
#    tar -xf /data/duckula-data.tar -C /data/ --strip-components=0; \
    rm -rf /opt/duckula.tar; \
#    rm -rf /data/duckula-data.tar; \
    chmod +x -R /opt/duckula/bin; \
    for path in \
		 /data/duckula-data \
		 /opt/duckula \
	; do \
		mkdir -p "$path"; \
		chown -R duckula:duckula "$path"; \
	done; 
#    apk del .duckuladepent; 
VOLUME /data/duckula-data/
VOLUME /opt/userconfig/
WORKDIR /opt/duckula
ENV PATH /opt/duckula/bin:$PATH

ENV DUCKULA_VERSION="2.0.0"
ENV DUCKULA_DATA="/data/duckula-data" \
	DUCKULA_HOME="/opt/duckula" \
	metricspath="/data/duckula-data/logs/metrics" \
	DelLoggerConfig="other"

COPY ./docker-entrypoint/docker-entrypoint.sh  /
RUN set -ex; \
    chmod  +x  /docker-entrypoint.sh; \
    chmod  777  /config.yaml; \
    chmod 444  /jmx_prometheus_javaagent-0.3.1.jar; 
#2723:jmx,jmxexport:2780,2113:debug,8080:web
EXPOSE 2723 2780 2113
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["help.sh"]